FROM node:18.12.1 AS Builder

WORKDIR /app

COPY . .

RUN npm install && \
npm run build:production

EXPOSE 7000

FROM node:18.12.1-alpine

WORKDIR /app
ENV PORT=7000

COPY --from=Builder /app/package.json .
COPY --from=Builder /app/prisma ./prisma
COPY --from=Builder /app/build ./build

RUN npm install --omit=dev
RUN npx prisma generate

CMD [ "npm","run", "start" ]
