FROM node:18.12.1 AS Builder

WORKDIR /app

COPY . .

RUN npm install && \
npm run build:production

FROM node:18.12.1-alpine

WORKDIR /app

COPY --from=Builder /app/package.json .
COPY --from=Builder /app/prisma ./prisma
COPY --from=Builder /app/build ./build

RUN npm install --omit=dev

RUN npm install prisma -g && \
npx prisma generate && \
npm remove -g prisma && \
npm remove -g npm

EXPOSE ${PORT}

CMD [ "npm","run", "start" ]
