@startuml Context
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(bankingCustomer, "Customer", "A customer of the bank")
System_Ext(gatewayMobile, "Gateway Mobile", "Application gateway")
System(referralService, "Referral Service", "Provides user referral code")

Rel_R(bankingCustomer, gatewayMobile, "Gets the referral methods")
Rel(gatewayMobile, referralService, "Gets the referral methods")

SHOW_LEGEND()

@enduml
