@startuml ReferralMethods

entity referral_methods {
 *id: uuid <<generated>> <<pk>>
 --
 *user_id: string(40) <<uk>>
 *code: string(10) <<uk>>
 *link: string(80) <<uk>>
 created_at: timestampz
 updated_at: timestampz
}

@enduml
