@startuml ReferralParameters

entity referral_parameters {
 *id: uuid <<generated>> <<pk>>
 --
 *user_id: uuid <<uk>>
 *code: string(10) <<uk>>
 *link: string(255) <<uk>>
 created_at: datetime
 updated_at: datetime
}

@enduml
