name: integration

on:
  push:
    branches-ignore:
      - "main"
  workflow_dispatch:
    branches-ignore:
      - "main"

jobs:
  lint:
    container:
      image: node:18.12.1
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Setup environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install NPM dependencies
        run: npm install
      - name: Check code lint
        run: npm run lint
      - name: Cleanup
        run: rm -rf *

  test:
    container:
      env:
        DATABASE_URL: 'postgresql://postgres:postgres@database:5432/db_testing'
        PORT: 7000
      image: node:18.12.1
    runs-on: ubuntu-latest
    services:
      database:
        image: postgres:14.6-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: db_testing
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Setup environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install NPM dependencies
        run: npm install
      #- name: Create database structure
      #  run: npm run db:deploy
      #- name: Check code tests
      #  run: npm run test:ci
      #- name: Reset database structure
      #  run: npm run db:reset
      - name: Cleanup
        run: rm -rf *
